theme: jekyll-theme-cayman
title: "PowerShell Modules"
show_downloads: true

pages_list:
  home: 'https://crispybaccoon.github.io/modules-powershell/'
  modules: 'https://crispybaccoon.github.io/modules-powershell/modules/'
  Add-Readme: 'https://crispybaccoon.github.io/modules-powershell/modules/Add-Readme/'
  PSRepository: 'https://crispybaccoon.github.io/modules-powershell/modules/PSRepository/'
  
